version: '3.8'
services:
  backend:
    build: ./backend
    container_name: linux_security_backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
    # - DB_URI=mongodb://mongo:27017/linux_security  
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: linux_security_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo: 
    image: mongo
    container_name: linux_security_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
